# Generated by Django 5.2.12 on 2026-05-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patien',
        ),
    ]
