# Generated by Django 5.2.12 on 2026-05-18 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_alter_patient_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
