# Generated by Django 5.2.12 on 2026-05-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profileImage',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
