# Generated by Django 5.2.12 on 2026-05-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profileImage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile/'),
        ),
    ]
